import type { RoadmapRow, AchievementRow } from "./schema";

export const seedRoadmap: RoadmapRow[] = [
  {
    id: 1,
    year: "2019",
    titleAr: "بداية الرحلة",
    titleEn: "The Journey Begins",
    descAr: "التحقت بكلية الهندسة قسم القوى الكهربائية، وبدأت أبني أساساً قوياً في الرياضيات والفيزياء.",
    descEn: "Enrolled in the Faculty of Engineering, Electrical Power department — building a strong foundation in math and physics.",
    sortOrder: 1,
  },
  {
    id: 2,
    year: "2021",
    titleAr: "أول مشروع عملي",
    titleEn: "First Real Project",
    descAr: "تصميم منظومة طاقة شمسية صغيرة لمنزل، وتعلّمت كيف تتحول المعادلات إلى واقع.",
    descEn: "Designed a small residential solar system — learning how equations turn into reality.",
    sortOrder: 2,
  },
  {
    id: 3,
    year: "2023",
    titleAr: "التخصص في الشبكات الذكية",
    titleEn: "Smart Grids Specialization",
    descAr: "تعمّقت في دراسة الشبكات الذكية وأنظمة التحكم وحماية القدرة الكهربائية.",
    descEn: "Specialized in smart grids, control systems, and power protection.",
    sortOrder: 3,
  },
  {
    id: 4,
    year: "2025",
    titleAr: "التخرج والانطلاق",
    titleEn: "Graduation",
    descAr: "تخرجت كمهندس قوى كهربائية، مستعداً لخوض السوق العملي والمساهمة في مشاريع الطاقة النظيفة.",
    descEn: "Graduated as an Electrical Power Engineer, ready to contribute to clean-energy projects.",
    sortOrder: 4,
  },
  {
    id: 5,
    year: "2026 →",
    titleAr: "الطموح القادم",
    titleEn: "What's Next",
    descAr: "العمل على مشاريع طاقة متجددة على مستوى إقليمي، وبناء خبرة في تصميم محطات الطاقة الشمسية.",
    descEn: "Working on regional renewable-energy projects and gaining expertise in solar plant design.",
    sortOrder: 5,
  },
];

export const seedAchievements: AchievementRow[] = [
  {
    id: 1,
    year: "2022",
    titleAr: "المركز الأول — مسابقة تصميم",
    titleEn: "1st Place — Design Competition",
    descAr: "فريقي حصل على المركز الأول في مسابقة الجامعة لتصميم منظومات الطاقة.",
    descEn: "My team took 1st place in the university energy-systems design competition.",
    icon: "trophy",
    imageUrl: "",
    videoUrl: "",
    media: "[]",
    sortOrder: 1,
  },
  {
    id: 2,
    year: "2024",
    titleAr: "تدريب في شركة كهرباء كبرى",
    titleEn: "Internship at a Major Utility",
    descAr: "تدريب صيفي على عمليات النقل والتوزيع وحماية الشبكة.",
    descEn: "Summer internship covering transmission, distribution, and grid protection.",
    icon: "bolt",
    imageUrl: "",
    videoUrl: "",
    media: "[]",
    sortOrder: 2,
  },
  {
    id: 3,
    year: "2024",
    titleAr: "شهادة في أنظمة الطاقة الشمسية",
    titleEn: "Solar Systems Certification",
    descAr: "إتمام شهادة احترافية في تصميم وتشغيل منظومات الطاقة الشمسية.",
    descEn: "Completed a professional certification in solar PV system design and operation.",
    icon: "sun",
    imageUrl: "",
    videoUrl: "",
    media: "[]",
    sortOrder: 3,
  },
  {
    id: 4,
    year: "2025",
    titleAr: "مشروع التخرج بامتياز",
    titleEn: "Graduation Project — Distinction",
    descAr: "مشروع تخرج عن إدارة الطلب في الشبكات الذكية، حصل على تقدير امتياز.",
    descEn: "Graduation project on demand-side management in smart grids, awarded distinction.",
    icon: "spark",
    imageUrl: "",
    videoUrl: "",
    media: "[]",
    sortOrder: 4,
  },
];
